- name: Demo on filters
  hosts: localhost
  vars: 
    NAME: MaNnaM saRatH 
  tasks:
  - name: convert into upper case
    debug:
      msg: "Hello {{ NAME | upper }}"

  - name: convert into lower case
    debug:
      msg: "Hello {{ NAME | lower }}"
  
  - name: Printing undefined variable
    debug:
      msg: "Leveraging new skill sets {{ COURSE | default(DevOps) }}"

# Variable can be declared at Play level, task level, Inventory, from seperate file (or) from prompt.
# But here i didn't set it from where variable is defined
# now DevOps value has defined to Course variable  